-- =============================================================================
-- 064 - imported expenses move to the dates she wrote (B-86)
-- =============================================================================
-- NOT APPLIED by the author. Run DIAGNOSTIC_expense_dates_before_064.sql first,
-- `npm run backup`, then this. Generated by database/gen-expense-date-fix.mjs from
-- her workbook: __ROWS__ lines before the August 2026 block, __MOVING__ of them
-- stored under a date she did not write.
--
-- Sean's decision, 2026-09-30: correct them. Not a correction of her book - the
-- import misread it, so this makes the database match it, as 032 did for income.
--   1. A typed Date was stored one day early (the 032 defect, never fixed for expenses).
--   2. A blank Date (her "same day as the line above") was stored on the 1st, and
--      "YEAR 2026" was not recognised, so 2026 lines were filed under 2025.
--   3. The June 2026 electric bill "Electricbill (May26)" holds only the Main House
--      share (P5,688.67); her workbook reads P20,652.80, adding the Boarding House's
--      P14,964.13. It is brought to her figure, dated 2026-06-04 as she wrote it
--      (stored 2026-06-03, the one-day-early defect).
--
-- HOW IT MATCHES. This was written without access to the live table, so nothing is
-- matched by id. A stored entry is paired with a workbook line on the date the
-- importer stored, the supplier, the category, the total and the split across
-- areas; a group moves only when the database holds exactly as many entries as the
-- workbook has lines for it. Anything else - an entry she typed into the system
-- herself, one edited since, a line she changed in the workbook later - is left
-- exactly as it is, and counted in the record this writes.
--
-- Money does not change except the electric bill: only expense_date moves, so
-- totals per year and month move with it. ONE statement (a single DO block), so it
-- runs whole in the SQL editor; an error anywhere undoes all of it.
-- =============================================================================

DO $$
DECLARE
  moved bigint;
  paired bigint;
  sheet_left bigint;
  db_left bigint;
  electric text := 'not found, left as is';
  eid uuid;
  cnt bigint;
BEGIN
  -- 3. The June electric bill, first: its workbook line carries the corrected total.
  SELECT count(*) INTO cnt FROM monthly_expense_entries
  WHERE or_supplier = 'Electricbill (May26)' AND total_expenses = 20652.80;
  IF cnt > 0 THEN
    electric := 'already P20,652.80, left as is';
  ELSE
    SELECT count(*), min(e.id::text)::uuid INTO cnt, eid FROM monthly_expense_entries e
    WHERE e.or_supplier = 'Electricbill (May26)' AND e.total_expenses = 5688.67
      AND e.expense_date IN (DATE '2026-06-03', DATE '2026-06-04')
      AND (SELECT count(*) FROM expense_property_allocations x WHERE x.expense_entry_id = e.id) = 1
      AND EXISTS (SELECT 1 FROM expense_property_allocations x WHERE x.expense_entry_id = e.id
                  AND x.property_area::text = 'Main House' AND x.amount = 5688.67);
    IF cnt = 1 THEN
      INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount)
      VALUES (eid, 'Boarding House'::property_area_type, 14964.13);
      UPDATE monthly_expense_entries SET total_expenses = 20652.80, expense_date = DATE '2026-06-04', updated_at = NOW()
      WHERE id = eid;
      electric := 'P5,688.67 (Main House) to P20,652.80 (+ Boarding House P14,964.13), dated 2026-06-04';
    ELSIF cnt > 1 THEN
      RAISE EXCEPTION '064 stopped, nothing changed: % entries look like the June electric bill. Send this message.', cnt;
    END IF;
  END IF;

  -- 1 and 2. The dates.
  WITH
    fix AS (
      SELECT f.r, f.o, f.n, trim(f.s) AS s, lower(f.c) AS c, f.t, f.a
      FROM jsonb_to_recordset('__DATA__'::jsonb) AS f(r int, o date, n date, s text, c text, t numeric, a text)
    ),
    stored AS (
      SELECT e.id, e.expense_date AS o, trim(e.or_supplier) AS s,
             lower(e.category_code) AS c, e.total_expenses AS t,
             coalesce((SELECT string_agg(x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00'), '|'
                                         ORDER BY x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00') COLLATE "C")
                       FROM expense_property_allocations x WHERE x.expense_entry_id = e.id), '') AS a
      FROM monthly_expense_entries e
      WHERE e.expense_date < DATE '2026-08-01'
    ),
    sk AS (SELECT o, s, c, t, a, count(*) AS n_sheet, array_agg(n ORDER BY n) AS news, array_agg(r ORDER BY n) AS rows_
           FROM fix GROUP BY o, s, c, t, a),
    dk AS (SELECT o, s, c, t, a, count(*) AS n_db, array_agg(id ORDER BY id) AS ids
           FROM stored GROUP BY o, s, c, t, a),
    ok AS (SELECT sk.*, dk.ids FROM sk JOIN dk USING (o, s, c, t, a) WHERE sk.n_sheet = dk.n_db),
    pairs AS (SELECT u.id, u.new_date FROM ok, unnest(ok.ids, ok.news) AS u(id, new_date))

  SELECT (SELECT count(*) FROM pairs),
         (SELECT count(*) FROM fix f WHERE NOT EXISTS (SELECT 1 FROM ok WHERE (ok.o, ok.s, ok.c, ok.t, ok.a) = (f.o, f.s, f.c, f.t, f.a))),
         (SELECT count(*) FROM stored s WHERE NOT EXISTS (SELECT 1 FROM ok WHERE s.id = ANY(ok.ids)))
  INTO paired, sheet_left, db_left;

  WITH
    fix AS (
      SELECT f.r, f.o, f.n, trim(f.s) AS s, lower(f.c) AS c, f.t, f.a
      FROM jsonb_to_recordset('__DATA__'::jsonb) AS f(r int, o date, n date, s text, c text, t numeric, a text)
    ),
    stored AS (
      SELECT e.id, e.expense_date AS o, trim(e.or_supplier) AS s,
             lower(e.category_code) AS c, e.total_expenses AS t,
             coalesce((SELECT string_agg(x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00'), '|'
                                         ORDER BY x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00') COLLATE "C")
                       FROM expense_property_allocations x WHERE x.expense_entry_id = e.id), '') AS a
      FROM monthly_expense_entries e
      WHERE e.expense_date < DATE '2026-08-01'
    ),
    sk AS (SELECT o, s, c, t, a, count(*) AS n_sheet, array_agg(n ORDER BY n) AS news, array_agg(r ORDER BY n) AS rows_
           FROM fix GROUP BY o, s, c, t, a),
    dk AS (SELECT o, s, c, t, a, count(*) AS n_db, array_agg(id ORDER BY id) AS ids
           FROM stored GROUP BY o, s, c, t, a),
    ok AS (SELECT sk.*, dk.ids FROM sk JOIN dk USING (o, s, c, t, a) WHERE sk.n_sheet = dk.n_db),
    pairs AS (SELECT u.id, u.new_date FROM ok, unnest(ok.ids, ok.news) AS u(id, new_date))

  UPDATE monthly_expense_entries e
     SET expense_date = p.new_date, updated_at = NOW()
    FROM pairs p
   WHERE e.id = p.id AND e.expense_date <> p.new_date;
  GET DIAGNOSTICS moved = ROW_COUNT;

  IF moved > 0 OR electric NOT LIKE '%left as is' THEN
    INSERT INTO audit_logs (action, entity_type, entity_id, new_values, ip_address)
    VALUES ('AUDIT_CORRECTION', 'EXPENSE_ENTRY', '00000000-0000-0000-0000-000000000000',
            jsonb_build_object(
              'note', 'Imported expense dates moved to the dates she wrote: typed dates had been stored a day early, and blank dates on the 1st of the month with 2026 lines under 2025. Only the date changed.',
              'moved', moved, 'paired_with_workbook', paired,
              'workbook_lines_unmatched', sheet_left, 'stored_entries_unmatched_left_as_is', db_left,
              'june_electric_bill', electric,
              'reference', 'migration 064, B-86, Sean''s decision 2026-09-30'),
            NULL);
  ELSE
    RAISE NOTICE '064: nothing to move. Already applied, or nothing matched.';
  END IF;
END $$;

-- "Success. No rows returned" means it ran. Check afterwards:
-- SELECT new_values FROM audit_logs WHERE action = 'AUDIT_CORRECTION' ORDER BY created_at DESC LIMIT 1;
-- Then run the diagnostic again: "will move" should read 0.
