-- =============================================================================
-- DIAGNOSTIC for 064 - what the expense-date correction would do. READ ONLY.
-- =============================================================================
-- Generated by database/gen-expense-date-fix.mjs from her workbook (__ROWS__ lines
-- before the August 2026 block, __MOVING__ of them stored under a different date).
-- One table: the summary first, then up to 40 workbook lines that match no
-- stored entry, and up to 40 stored entries that match no workbook line. Those
-- are left exactly as they are by 064. Section "year" shows the effect.
-- =============================================================================
WITH
    fix AS (
      SELECT f.r, f.o, f.n, trim(f.s) AS s, lower(f.c) AS c, f.t, f.a
      FROM jsonb_to_recordset('__DATA__'::jsonb) AS f(r int, o date, n date, s text, c text, t numeric, a text)
    ),
    stored AS (
      SELECT e.id, e.expense_date AS o, trim(e.or_supplier) AS s,
             lower(e.category_code) AS c, e.total_expenses AS t,
             coalesce((SELECT string_agg(x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00'), '|'
                                         ORDER BY x.property_area::text || ':' || to_char(x.amount, 'FM9999999990.00') COLLATE "C")
                       FROM expense_property_allocations x WHERE x.expense_entry_id = e.id), '') AS a
      FROM monthly_expense_entries e
      WHERE e.expense_date < DATE '2026-08-01'
    ),
    sk AS (SELECT o, s, c, t, a, count(*) AS n_sheet, array_agg(n ORDER BY n) AS news, array_agg(r ORDER BY n) AS rows_
           FROM fix GROUP BY o, s, c, t, a),
    dk AS (SELECT o, s, c, t, a, count(*) AS n_db, array_agg(id ORDER BY id) AS ids
           FROM stored GROUP BY o, s, c, t, a),
    ok AS (SELECT sk.*, dk.ids FROM sk JOIN dk USING (o, s, c, t, a) WHERE sk.n_sheet = dk.n_db),
    pairs AS (SELECT u.id, u.new_date FROM ok, unnest(ok.ids, ok.news) AS u(id, new_date))
,
    moved AS (SELECT p.id, s.o AS old_date, p.new_date FROM pairs p JOIN stored s ON s.id = p.id WHERE s.o <> p.new_date),
    sheet_left AS (SELECT f.* FROM fix f WHERE NOT EXISTS (SELECT 1 FROM ok WHERE (ok.o, ok.s, ok.c, ok.t, ok.a) = (f.o, f.s, f.c, f.t, f.a))),
    db_left AS (SELECT s.* FROM stored s WHERE NOT EXISTS (SELECT 1 FROM ok WHERE s.id = ANY(ok.ids)))
SELECT * FROM (
  SELECT 1 AS k, 'workbook lines before Aug 2026' AS item, (SELECT count(*) FROM fix)::text AS value, '' AS detail
  UNION ALL SELECT 2, 'stored entries before Aug 2026', (SELECT count(*) FROM stored)::text, ''
  UNION ALL SELECT 3, 'paired with the workbook', (SELECT count(*) FROM pairs)::text, ''
  UNION ALL SELECT 4, 'will move to the date she wrote', (SELECT count(*) FROM moved)::text, ''
  UNION ALL SELECT 5, 'of those, from 2025 into 2026', (SELECT count(*) FROM moved WHERE date_part('year', old_date) = 2025 AND date_part('year', new_date) = 2026)::text, ''
  UNION ALL SELECT 6, 'workbook lines with no stored match (left alone)', (SELECT count(*) FROM sheet_left)::text, ''
  UNION ALL SELECT 7, 'stored entries with no workbook match (left alone)', (SELECT count(*) FROM db_left)::text, ''
  UNION ALL SELECT 8, 'June electric bill as stored', coalesce((SELECT string_agg(e.expense_date || ' P' || e.total_expenses, ', ')
                FROM monthly_expense_entries e WHERE e.or_supplier = 'Electricbill (May26)'), 'not found'), 'her workbook: 2026-06-04 P20652.80 (BH 14964.13 + MH 5688.67)'
  UNION ALL SELECT 9, 'year ' || y, cnt_before::text || ' entries now', 'after 064: ' || cnt_after
  FROM (SELECT y, sum(b) AS cnt_before, sum(a_) AS cnt_after FROM (
          SELECT date_part('year', s.o)::int AS y, 1 AS b, 0 AS a_ FROM stored s
          UNION ALL SELECT date_part('year', coalesce(m.new_date, s.o))::int, 0, 1 FROM stored s LEFT JOIN moved m ON m.id = s.id) q
        GROUP BY y) yy
  UNION ALL SELECT * FROM (SELECT 10, 'workbook line ' || r || ', no match', o::text, left(s, 40) || ' P' || t FROM sheet_left ORDER BY r LIMIT 40) x
  UNION ALL SELECT * FROM (SELECT 11, 'stored, no match', o::text, left(s, 40) || ' P' || t FROM db_left ORDER BY o LIMIT 40) y
) z ORDER BY k, item, value;
