-- 062: the owner's receipts and expenses for August 2026, from her updated workbook - ADDITIVE ONLY
--
-- Run `npm run backup` first (taken: backups/2026-09-30T02-35-46, 937 income records,
-- PHP 8,086,250.00). Adds 15 income records and 34 expense entries. Changes and removes nothing.
--
-- SOURCE
-- ------
-- "Michelles-BH-Report-Income-and-Expenses-fr-Yr-2024-up.xlsx" as updated by the owner through the
-- end of August 2026, handed over by Loyd on 2026-09-30 (the testing day), when the database's last
-- receipt was dated 8 August. Generated by `database/import-ledger-update.mjs`, which parses with the
-- original importer's rules (migrate-past-records.mjs, whose delete-and-reimport must never run
-- again) and compares every row with the database. Applied the same day through that script's
-- --apply, which inserts exactly these rows; every statement below is guarded by NOT EXISTS on the
-- same key, so running this file afterwards (or twice) adds nothing.
--
-- WHAT WENT IN
-- ------------
-- Income, the AUGUST 2026 block: 15 receipts, rent PHP 124,250, water PHP 3,600, every one linked to
-- its tenant by name (the original rule). Units 1d 1h 2b 2e 2f 2g 3d 3f 3g B1F B2F B2B B3F F2B LF.
-- Expenses dated in August 2026: 34 entries, PHP 234,244.78, which equals her own AUGUST TOTALS row
-- area by area (Boarding House 80,075.93; Main House 18,010.85; Back Apartment 7,000.00; Other /
-- Personal 129,158.00).
--
-- WHAT DID NOT, AND WHY
-- ---------------------
--   16 August lines with NO date paid (1a 1b 1c 1f 1g 2a 2c 2d 3a 3b 3c 3e B3B F1 F2F LB): lines she
--      lays out for tenants who have not paid yet, most with a half-typed "INV#52" or last month's
--      number. The original importer would have filed each as PAID on 1 August.
--    1 August line for 1e carried forward from July: INV#5221, 25 July, already stored for
--      15 Jul - 14 Aug; only the period had been moved on.
--    7 lines in older blocks that differ from the database because reviewed migrations corrected
--      them there (032's date fixes and the pinned anomalies OR#4839 and INVOICE#5120 among them).
--    1 expense: "Electricbill (May26)" 2026-06-04 is stored as PHP 5,688.67 (Main House only); the
--      workbook now reads PHP 20,652.80 with a Boarding House share of 14,964.13. Not added: it
--      would double-count the stored part. Left for the owner to confirm.
--
-- TWO TYPOS READ AS SHE MEANT THEM (the only departures from her exact text)
--   1h: Date Paid typed as text "29-Aug--26" (double dash, so Excel never stored a date) -> 2026-08-29.
--   B1F: rent period "Aug.10-Sep.9/25" on a line paid 12 August 2026 in the August 2026 block
--        -> 2026-08-10 .. 2026-09-09.
--
-- DATES
-- -----
-- Income dates are the dates she wrote (read in UTC; the one-day-early defect 032 corrected).
-- Expense dates are the dates she wrote, a blank Date cell read as the same day as the line above,
-- as her sheet is kept. NOTE: the 1,262 expense entries imported on 2026-08-28 do NOT follow either
-- rule - they are a day early where a date was typed (032's defect, never corrected for expenses)
-- and on the 1st of a month, with 2026 blocks filed under 2025, where the cell was blank (647
-- entries). That is recorded in BLOCKED_FOR_SEAN.md (B-86); this migration does not touch it.
--
-- VERIFY (expected: 952 live income records, PHP 8,086,250.00 + the 15 remitted; 1,296 expense
-- entries):
--   SELECT count(*), sum(remitted_amount) FROM monthly_income_records WHERE voided_at IS NULL;
--   SELECT count(*) FROM monthly_expense_entries;

BEGIN;

-- INCOME: one row per paid receipt in the workbook that the database did not hold.
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0100000-0000-0000-0000-000000000004', '226b3723-1578-4b93-b0d9-5a6ddee8dbd7', 2026, 8, '2026-08-12', 'Sandrine Jammeka Mariano', 'INV.#5237', '2026-08-09', '2026-09-08', 7250, 1, 200, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0100000-0000-0000-0000-000000000004' AND invoice_number = 'INV.#5237' AND date_paid = '2026-08-12' AND rent_amount = 7250); -- sheet row 1440, unit 1d
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0100000-0000-0000-0000-000000000008', 'fa730ca9-6cf9-4304-bd38-43054f6f5a3d', 2026, 8, '2026-08-29', 'Trisha Nicole Bellio', 'INV#5241', '2026-08-28', '2026-09-27', 6500, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0100000-0000-0000-0000-000000000008' AND invoice_number = 'INV#5241' AND date_paid = '2026-08-29' AND rent_amount = 6500); -- sheet row 1444, unit 1h
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0200000-0000-0000-0000-000000000002', '02b0cdee-0ab2-4bac-a6ec-916789f455ff', 2026, 8, '2026-08-20', 'Nikki Prollamante', 'INV#5239', '2026-08-10', '2026-09-09', 8500, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0200000-0000-0000-0000-000000000002' AND invoice_number = 'INV#5239' AND date_paid = '2026-08-20' AND rent_amount = 8500); -- sheet row 1446, unit 2b
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0200000-0000-0000-0000-000000000005', '0b237c18-fcb6-486a-89db-1c4997bdd7fd', 2026, 8, '2026-09-02', 'Sian Danver Morta', 'INV#5246', '2026-08-26', '2026-09-25', 8000, 1, 0, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0200000-0000-0000-0000-000000000005' AND invoice_number = 'INV#5246' AND date_paid = '2026-09-02' AND rent_amount = 8000); -- sheet row 1449, unit 2e
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0200000-0000-0000-0000-000000000006', '94ac88a3-ea22-4489-8469-1e27719fb2d3', 2026, 8, '2026-08-18', 'Christine Golpeo', 'INV#5238', '2026-08-15', '2026-09-14', 6500, 1, 0, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0200000-0000-0000-0000-000000000006' AND invoice_number = 'INV#5238' AND date_paid = '2026-08-18' AND rent_amount = 6500); -- sheet row 1450, unit 2f
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0200000-0000-0000-0000-000000000007', '74fce0a5-8787-4f18-8fa6-79cb2c09d315', 2026, 8, '2026-09-01', 'Grace Trina metillo', 'INV#5244', '2026-08-28', '2026-09-28', 6500, 1, 200, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0200000-0000-0000-0000-000000000007' AND invoice_number = 'INV#5244' AND date_paid = '2026-09-01' AND rent_amount = 6500); -- sheet row 1451, unit 2g
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0300000-0000-0000-0000-000000000004', 'f6eb33ef-6f8a-419a-86eb-43a949cb345d', 2026, 8, '2026-09-02', 'Alejandro Delarosa', 'INV#5245', '2026-08-15', '2026-09-14', 8500, 1, 200, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0300000-0000-0000-0000-000000000004' AND invoice_number = 'INV#5245' AND date_paid = '2026-09-02' AND rent_amount = 8500); -- sheet row 1455, unit 3d
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0300000-0000-0000-0000-000000000006', 'd6d3fcac-a9a6-4e76-b283-00fe4a73d72e', 2026, 8, '2026-08-29', 'Eunice Francisco', 'INV.#5242', '2026-08-25', '2026-09-24', 6500, 1, 200, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0300000-0000-0000-0000-000000000006' AND invoice_number = 'INV.#5242' AND date_paid = '2026-08-29' AND rent_amount = 6500); -- sheet row 1457, unit 3f
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'a0300000-0000-0000-0000-000000000007', '71e0165e-8eaf-40b2-aa02-691b97e1fef4', 2026, 8, '2026-08-29', 'Ann Kristine Diaz', 'INV#5240', '2026-08-25', '2026-09-24', 7000, 1, 0, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'a0300000-0000-0000-0000-000000000007' AND invoice_number = 'INV#5240' AND date_paid = '2026-08-29' AND rent_amount = 7000); -- sheet row 1458, unit 3g
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'b0100000-0000-0000-0000-000000000001', '89efd406-2747-4413-9a3b-803920866aef', 2026, 8, '2026-08-12', 'Arvin Vega', 'N/A-B1F-8-2026', '2026-08-10', '2026-09-09', 10000, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'b0100000-0000-0000-0000-000000000001' AND invoice_number = 'N/A-B1F-8-2026' AND date_paid = '2026-08-12' AND rent_amount = 10000); -- sheet row 1461, unit B1F
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'b0200000-0000-0000-0000-000000000001', 'ae5197de-1a39-4bf4-904b-d3b8370cbae9', 2026, 8, '2026-08-28', 'Anna Sherra Jalmasco', 'N/A-B2F-8-2026', '2026-08-21', '2026-09-20', 10000, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'b0200000-0000-0000-0000-000000000001' AND invoice_number = 'N/A-B2F-8-2026' AND date_paid = '2026-08-28' AND rent_amount = 10000); -- sheet row 1462, unit B2F
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'b0200000-0000-0000-0000-000000000002', 'af9c1136-68fd-423e-9197-6a8ba1f71dd7', 2026, 8, '2026-08-10', 'Krizza Bellena', 'N/A-B2B-8-2026', '2026-08-03', '2026-09-02', 12000, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'b0200000-0000-0000-0000-000000000002' AND invoice_number = 'N/A-B2B-8-2026' AND date_paid = '2026-08-10' AND rent_amount = 12000); -- sheet row 1463, unit B2B
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'b0300000-0000-0000-0000-000000000001', '731ace4e-2592-4fe2-a185-cfa93fb7260e', 2026, 8, '2026-08-22', 'Janna Berlarmino', 'N/A-B3F-8-2026', '2026-08-12', '2026-09-11', 12000, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'b0300000-0000-0000-0000-000000000001' AND invoice_number = 'N/A-B3F-8-2026' AND date_paid = '2026-08-22' AND rent_amount = 12000); -- sheet row 1464, unit B3F
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'd0200000-0000-0000-0000-000000000002', '43627dec-7972-49b6-bef0-c5b9dfcbb23d', 2026, 8, '2026-08-25', 'Alfred John Laurinaria', 'N/A-F2B-8-2026', '2026-08-15', '2026-09-14', 10000, 2, 400, 0, 'Cash', false, 0, 0, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'd0200000-0000-0000-0000-000000000002' AND invoice_number = 'N/A-F2B-8-2026' AND date_paid = '2026-08-25' AND rent_amount = 10000); -- sheet row 1472, unit F2B
INSERT INTO monthly_income_records (room_id, tenant_profile_id, year, month, date_paid, contact_name, invoice_number, rent_period_start, rent_period_end, rent_amount, occupants, water_payment, gbg_fee, payment_method, is_linda_billing, linda_electricity_charge, linda_water_charge, verification_status)
  SELECT 'e0100000-0000-0000-0000-000000000001', '9b16eab1-d76e-4629-a6c1-3d9cbceedf5e', 2026, 8, '2026-08-28', 'Gayon LGPT', 'N/A-LF-8-2026', '2026-08-13', '2026-09-12', 5000, 2, 0, 0, 'Cash', true, 325, 400, 'Verified'
  WHERE NOT EXISTS (SELECT 1 FROM monthly_income_records WHERE room_id = 'e0100000-0000-0000-0000-000000000001' AND invoice_number = 'N/A-LF-8-2026' AND date_paid = '2026-08-28' AND rent_amount = 5000); -- sheet row 1476, unit LF

-- EXPENSES: each entry, then its area allocations (the total follows the allocations by trigger).
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-01', 'Wilcon (bh)', '8', 2502.25
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-01' AND or_supplier = 'Wilcon (bh)' AND category_code = '8' AND total_expenses = 2502.25) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 2502.25)) AS v(area, amount); -- sheet row 1368
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-01', 'Randy Millete', '8', 4200
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-01' AND or_supplier = 'Randy Millete' AND category_code = '8' AND total_expenses = 4200) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 4200)) AS v(area, amount); -- sheet row 1370
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-01', 'Jonard Granadillos', '8', 4200
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-01' AND or_supplier = 'Jonard Granadillos' AND category_code = '8' AND total_expenses = 4200) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 4200)) AS v(area, amount); -- sheet row 1371
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-01', 'Wilcon Depot (bh)', '8', 2250
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-01' AND or_supplier = 'Wilcon Depot (bh)' AND category_code = '8' AND total_expenses = 2250) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 2250)) AS v(area, amount); -- sheet row 1372
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-01', 'Maxifuel (vios)', '9', 1500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-01' AND or_supplier = 'Maxifuel (vios)' AND category_code = '9' AND total_expenses = 1500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 1500)) AS v(area, amount); -- sheet row 1373
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-03', 'Viscara (coke,cigarette fe)', '10', 1090
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-03' AND or_supplier = 'Viscara (coke,cigarette fe)' AND category_code = '10' AND total_expenses = 1090) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 1090)) AS v(area, amount); -- sheet row 1374
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-03', 'Hong Enterprises', '10', 429
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-03' AND or_supplier = 'Hong Enterprises' AND category_code = '10' AND total_expenses = 429) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 429)) AS v(area, amount); -- sheet row 1375
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-03', 'Legazpi Water Distric (July 26)', '7', 714
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-03' AND or_supplier = 'Legazpi Water Distric (July 26)' AND category_code = '7' AND total_expenses = 714) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 714)) AS v(area, amount); -- sheet row 1376
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-03', 'Electricbill (july 26)', '7', 24501.53
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-03' AND or_supplier = 'Electricbill (july 26)' AND category_code = '7' AND total_expenses = 24501.53) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 16424.68), ('Main House', 8076.85)) AS v(area, amount); -- sheet row 1377
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-04', 'Wilcon depot (bh)', '8', 2811
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-04' AND or_supplier = 'Wilcon depot (bh)' AND category_code = '8' AND total_expenses = 2811) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 2811)) AS v(area, amount); -- sheet row 1378
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-06', 'Wilcon Depot (penthouse)', '8', 4419.5
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-06' AND or_supplier = 'Wilcon Depot (penthouse)' AND category_code = '8' AND total_expenses = 4419.5) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 4419.5)) AS v(area, amount); -- sheet row 1379
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-08', 'Metro Gaizano (jug mh)', '10', 1099
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-08' AND or_supplier = 'Metro Gaizano (jug mh)' AND category_code = '10' AND total_expenses = 1099) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Main House', 1099)) AS v(area, amount); -- sheet row 1380
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-08', 'Randy Millete', '8', 4200
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-08' AND or_supplier = 'Randy Millete' AND category_code = '8' AND total_expenses = 4200) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 4200)) AS v(area, amount); -- sheet row 1382
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-08', 'Jonard Granadillos', '8', 4200
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-08' AND or_supplier = 'Jonard Granadillos' AND category_code = '8' AND total_expenses = 4200) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 4200)) AS v(area, amount); -- sheet row 1383
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-08', 'Wilcon Depot (penthouse)', '8', 1204.5
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-08' AND or_supplier = 'Wilcon Depot (penthouse)' AND category_code = '8' AND total_expenses = 1204.5) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 1204.5)) AS v(area, amount); -- sheet row 1384
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-09', '808 Enterprises (gaz vios)', '9', 1500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-09' AND or_supplier = '808 Enterprises (gaz vios)' AND category_code = '9' AND total_expenses = 1500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 1500)) AS v(area, amount); -- sheet row 1385
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-10', 'Wilcon Depot (penthouse)', '8', 3101
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-10' AND or_supplier = 'Wilcon Depot (penthouse)' AND category_code = '8' AND total_expenses = 3101) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 3101)) AS v(area, amount); -- sheet row 1386
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-11', 'Abuloy (Jun Toledo)', '10', 5000
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-11' AND or_supplier = 'Abuloy (Jun Toledo)' AND category_code = '10' AND total_expenses = 5000) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 5000)) AS v(area, amount); -- sheet row 1387
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-12', 'Atty.Basaltan  (fe last will)', '10', 75000
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-12' AND or_supplier = 'Atty.Basaltan  (fe last will)' AND category_code = '10' AND total_expenses = 75000) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 75000)) AS v(area, amount); -- sheet row 1388
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-12', 'Enternit', '7', 735
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-12' AND or_supplier = 'Enternit' AND category_code = '7' AND total_expenses = 735) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 735)) AS v(area, amount); -- sheet row 1389
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-14', 'Market (fe party)', '10', 5000
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-14' AND or_supplier = 'Market (fe party)' AND category_code = '10' AND total_expenses = 5000) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 5000)) AS v(area, amount); -- sheet row 1390
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-14', 'Cigarette (fe)', '10', 1750
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-14' AND or_supplier = 'Cigarette (fe)' AND category_code = '10' AND total_expenses = 1750) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 1750)) AS v(area, amount); -- sheet row 1391
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-14', 'Randy Millete', '8', 3500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-14' AND or_supplier = 'Randy Millete' AND category_code = '8' AND total_expenses = 3500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 3500)) AS v(area, amount); -- sheet row 1393
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-14', 'Jonard Granadillos', '8', 3500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-14' AND or_supplier = 'Jonard Granadillos' AND category_code = '8' AND total_expenses = 3500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 3500)) AS v(area, amount); -- sheet row 1394
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-18', 'Bestbake (sanseval cake)', '10', 889
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-18' AND or_supplier = 'Bestbake (sanseval cake)' AND category_code = '10' AND total_expenses = 889) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 889)) AS v(area, amount); -- sheet row 1395
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-20', 'SSS (michelle) jul.26', '6b', 760
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-20' AND or_supplier = 'SSS (michelle) jul.26' AND category_code = '6b' AND total_expenses = 760) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 760)) AS v(area, amount); -- sheet row 1396
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-20', 'Randy Millete', '8', 3500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-20' AND or_supplier = 'Randy Millete' AND category_code = '8' AND total_expenses = 3500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Back Apartment', 3500)) AS v(area, amount); -- sheet row 1398
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-20', 'Jonard Granadillos', '8', 3500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-20' AND or_supplier = 'Jonard Granadillos' AND category_code = '8' AND total_expenses = 3500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Back Apartment', 3500)) AS v(area, amount); -- sheet row 1399
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-20', 'Aqulife Hobby Shop', '10', 2335
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-20' AND or_supplier = 'Aqulife Hobby Shop' AND category_code = '10' AND total_expenses = 2335) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Main House', 2335)) AS v(area, amount); -- sheet row 1400
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-27', 'Money (bonus) Lydia Millete', '10', 20000
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-27' AND or_supplier = 'Money (bonus) Lydia Millete' AND category_code = '10' AND total_expenses = 20000) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 20000)) AS v(area, amount); -- sheet row 1401
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-27', 'Money(bonus) Randy Millete', '10', 20000
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-27' AND or_supplier = 'Money(bonus) Randy Millete' AND category_code = '10' AND total_expenses = 20000) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Other Expenses / Personal', 20000)) AS v(area, amount); -- sheet row 1402
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-28', 'Wilcon Depot (bh)', '8', 1854
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-28' AND or_supplier = 'Wilcon Depot (bh)' AND category_code = '8' AND total_expenses = 1854) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 1854)) AS v(area, amount); -- sheet row 1403
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-31', 'Salaries (michelle)Aug.1-31,2026)', '6', 16500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-31' AND or_supplier = 'Salaries (michelle)Aug.1-31,2026)' AND category_code = '6' AND total_expenses = 16500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 10000), ('Main House', 6500)) AS v(area, amount); -- sheet row 1404
WITH e AS (INSERT INTO monthly_expense_entries (expense_date, or_supplier, category_code, total_expenses)
  SELECT '2026-08-31', 'Janitorial', '3', 6500
  WHERE NOT EXISTS (SELECT 1 FROM monthly_expense_entries WHERE expense_date = '2026-08-31' AND or_supplier = 'Janitorial' AND category_code = '3' AND total_expenses = 6500) RETURNING id)
INSERT INTO expense_property_allocations (expense_entry_id, property_area, amount) SELECT e.id, v.area::property_area_type, v.amount FROM e, (VALUES ('Boarding House', 6500)) AS v(area, amount); -- sheet row 1405

COMMIT;
