#!/usr/bin/env node
/**
 * Turns the testing day's observation sheets into Chapter 4's Table 11C.
 *
 * Run:  node scripts/survey/compute-uat.mjs <observations.csv>
 *
 * Type each observation sheet line into a copy of `uat-observations-template.csv` (same folder):
 *   tester      T1, T2, ... (never a name)
 *   device      e.g. "Android Chrome", "iPhone Safari"
 *   case        T-01 ... T-18, as on the sheet
 *   start, end  clock times, HH:MM or HH:MM:SS
 *   success     P (done alone), PH (done with help), F (not done), NT (not tried)
 *   errors      wrong taps that led somewhere unintended (a number; blank = 0)
 *   help_given, said   free text, for the interpretation paragraph
 *
 * Output: Table 11C in Chapter 4's layout (task groups as the chapter lists them), then the same
 * per single case, then what testers said. Quality in use per ISO/IEC 25010: completion without help
 * is effectiveness, time on task is efficiency.
 */
import fs from 'node:fs';

const file = process.argv[2];
if (!file) { console.error('usage: node scripts/survey/compute-uat.mjs <observations.csv>'); process.exit(1); }

function parseCsv(text) {
  const rows = []; let row = [], cell = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) { if (c === '"' && text[i + 1] === '"') { cell += '"'; i++; } else if (c === '"') q = false; else cell += c; }
    else if (c === '"') q = true;
    else if (c === ',') { row.push(cell); cell = ''; }
    else if (c === '\n' || c === '\r') { if (c === '\r' && text[i + 1] === '\n') i++; row.push(cell); rows.push(row); row = []; cell = ''; }
    else cell += c;
  }
  if (cell !== '' || row.length) { row.push(cell); rows.push(row); }
  return rows.filter((r) => r.some((v) => v.trim() !== ''));
}
const [head, ...rows] = parseCsv(fs.readFileSync(file, 'utf8').replace(/^﻿/, ''));
const col = (name) => head.findIndex((h) => h.trim().toLowerCase() === name);
const C = Object.fromEntries(['tester', 'device', 'case', 'start', 'end', 'success', 'errors', 'help_given', 'said'].map((n) => [n, col(n)]));
if (C.case < 0 || C.success < 0) { console.error('The CSV needs at least the "case" and "success" columns (see the template).'); process.exit(1); }

const secs = (t) => { const m = String(t ?? '').trim().match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/); return m ? +m[1] * 3600 + +m[2] * 60 + +(m[3] ?? 0) : null; };
const obs = rows.filter((r) => !/example row/i.test(r[C.said] ?? '')).map((r) => {
  const s = secs(r[C.start]), e = secs(r[C.end]);
  return {
    tester: (r[C.tester] ?? '').trim(), device: (r[C.device] ?? '').trim(), c: (r[C.case] ?? '').trim().toUpperCase(),
    ok: (r[C.success] ?? '').trim().toUpperCase(),
    time: s != null && e != null && e >= s ? e - s : null,
    errors: Number((r[C.errors] ?? '').trim() || 0),
    help: (r[C.help_given] ?? '').trim(), said: (r[C.said] ?? '').trim(),
  };
});
const median = (a) => { if (!a.length) return null; const s = [...a].sort((x, y) => x - y); const m = Math.floor(s.length / 2); return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };
const mean = (a) => a.length ? a.reduce((x, y) => x + y, 0) / a.length : null;

const GROUPS = [
  ['First sign-in and choosing a password (T-01, T-02)', ['T-01', 'T-02']],
  ['Finding their unit, rent and balance (T-03, T-04)', ['T-03', 'T-04']],
  ['Finding their payments (T-05, T-06)', ['T-05', 'T-06']],
  ['Sending a repair request with a photo (T-07 to T-09)', ['T-07', 'T-08', 'T-09']],
  ['Following up a request (T-10, T-11)', ['T-10', 'T-11']],
  ['Checking their details and notifications (T-12, T-13)', ['T-12', 'T-13']],
  ['Opening the GCash payment (T-14)', ['T-14']],
  ['Staying out of the owner\'s pages; signing out (T-15, T-16)', ['T-15', 'T-16']],
];

function line(label, set) {
  const tried = set.filter((o) => o.ok && o.ok !== 'NT');
  const testers = new Set(tried.map((o) => o.tester)).size;
  const p = tried.filter((o) => o.ok === 'P').length, ph = tried.filter((o) => o.ok === 'PH').length, f = tried.filter((o) => o.ok === 'F').length;
  const t = median(tried.map((o) => o.time).filter((x) => x != null));
  const e = mean(tried.map((o) => o.errors));
  const rate = tried.length ? `${((100 * p) / tried.length).toFixed(0)}%` : '';
  return `| ${label} | ${testers} | ${p} | ${ph} | ${f} | ${t ?? ''} | ${e == null ? '' : e.toFixed(1)} | ${rate} |`;
}

const out = [];
out.push(`<!-- Generated by scripts/survey/compute-uat.mjs from ${file.split(/[\\/]/).pop()}, ${new Date().toISOString().slice(0, 10)}. Counts are task attempts; "Tenants attempting" counts people. -->`, '');
out.push('**Table 11C.** Tenant Task Results', '');
out.push('| Task | Tenants attempting | Completed without help | Completed with help | Not completed | Median time (s) | Mean wrong turns | Completion without help |');
out.push('| :--- | --: | --: | --: | --: | --: | --: | --: |');
for (const [label, cases] of GROUPS) out.push(line(label, obs.filter((o) => cases.includes(o.c))));
out.push(line('**All tasks**', obs.filter((o) => /^T-(0[1-9]|1[0-6])$/.test(o.c))));
out.push('', '### Per case (supporting)', '', '| Case | Attempts | P | PH | F | Median time (s) | Mean wrong turns |', '| :-- | --: | --: | --: | --: | --: | --: |');
for (const c of [...new Set(obs.map((o) => o.c))].sort()) {
  const s = obs.filter((o) => o.c === c && o.ok !== 'NT');
  out.push(`| ${c} | ${s.length} | ${s.filter((o) => o.ok === 'P').length} | ${s.filter((o) => o.ok === 'PH').length} | ${s.filter((o) => o.ok === 'F').length} | ${median(s.map((o) => o.time).filter((x) => x != null)) ?? ''} | ${s.length ? mean(s.map((o) => o.errors)).toFixed(1) : ''} |`);
}
out.push('', '### Devices', '', ...[...new Set(obs.map((o) => `${o.tester}: ${o.device}`))].map((d) => `- ${d}`));
out.push('', '### Help given and what testers said (for the interpretation paragraph)');
for (const o of obs.filter((o) => o.help || o.said)) out.push(`- ${o.c} ${o.tester}${o.help ? ` - help: ${o.help}` : ''}${o.said ? ` - said: "${o.said}"` : ''}`);
const bad = obs.filter((o) => !['P', 'PH', 'F', 'NT'].includes(o.ok));
if (bad.length) out.push('', `> WARNING: ${bad.length} line(s) have a success value other than P, PH, F or NT and were not counted: ${bad.map((o) => `${o.c} ${o.tester} "${o.ok}"`).join(', ')}`);
process.stdout.write(out.join('\n') + '\n');
if (bad.length) process.exitCode = 2;
